### ISSUE TITLE
error handling in your Flask application

### ISSUE THREAD

**Issue by vidhsss** [KushagraSikka/rmbg_docker_for_ec2#4]
Here are some common error handling cases for your application:

	1.	File Not Uploaded: If no file is uploaded or the file field is missing, return a proper error message.
	2.	Unsupported File Format: If the uploaded file is not an image, return an error message.
	3.	Background Image Not Supported: If the uploaded background image is not in a valid format or cannot be processed, return an error message.
	4.	Multiple Files Error: If the multiple file upload functionality has issues, handle it gracefully.
	5.	Processing Error: Handle errors that occur during the image processing (rembg, Pillow, etc.).

**Comment by KushagraSikka** [comment]
Fixes:
1.	File Not Uploaded:
	•	Issue: If no file is uploaded or file is not in request.files.
	•	Fix: Added a check for 'file' not in request.files and return a clear error message.
	2.	Unsupported File Format:
	•	Issue: If a user uploads a file that’s not an image.
	•	Fix: Wrapped the image opening logic in a try-except block to handle UnidentifiedImageError. This provides a clear error message for unsupported image formats.
	3.	Background Image Format:
	•	Issue: If the background image is unsupported or cannot be processed.
	•	Fix: Added similar handling for the background image, returning a clear message if it’s invalid.
	4.	Multiple File Processing Errors:
	•	Issue: If processing multiple files leads to an issue.
	•	Fix: Implemented a loop that processes each file and added error handling for each, ensuring users get detailed error messages per file if processing fails.
	5.	Image Processing Errors:
	•	Issue: If an error occurs while processing the image (e.g., rembg error or Pillow error).
	•	Fix: Added a try-except block around the background removal process to catch any errors that might occur, such as memory issues or unexpected crashes.
